policy: "MlpPolicy"
policy_kwargs:
  net_arch:
    pi: [256, 256, 128]
    vf: [256, 256, 128]
  activation_fn: "torch.nn.ELU"
  ortho_init: True
n_steps: 2048
batch_size: 64
gamma: 0.99
learning_rate: 3.0e-4
ent_coef: 0.0
clip_range: 0.2
n_epochs: 10
gae_lambda: 0.95
max_grad_norm: 1.0
vf_coef: 0.5
seed: 42
device: "cuda"
normalize_input: True
normalize_value: True
verbose: 1